version: '3'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      app_net:
        ipv4_address: 172.20.0.2
    ports:
      - "3000:3000"
    cap_add:
      - NET_ADMIN

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    networks:
      app_net:
        ipv4_address: 172.20.0.3
    ports:
      - "3001:3001"
    depends_on:
      - main

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16